version: '3'

services:
  mysql:
    container_name: moneyandlove
    image: mysql:8.0.33
    ports:
      - 3306:3306
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: moneyandlovedb

  openvidu:
    image: openvidu/openvidu-dev:2.30.0
    ports:
      - "4443:4443"
    environment:
      OPENVIDU_SECRET: MY_SECRET
    restart: unless-stopped