version: '3'

services:
  mysql:
    container_name: moneyandlove-mysql
    image: mysql:8.0.33
    ports:
      - "3306:3306"
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: moneyandlovedb
    networks:
      - moneyandlove-network
  mongo:
    container_name: moneyandlove-mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: moneyandlovedb
    networks:
      - moneyandlove-network
  openvidu:
    container_name: moneyandlove-openvidu
    image: openvidu/openvidu-dev:2.30.0
    ports:
      - "4443:4443"
    environment:
      OPENVIDU_SECRET: MY_SECRET
    restart: unless-stopped
    networks:
      - moneyandlove-network
  redis:
    container_name: moneyandlove-redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - moneyandlove-network
networks:
  moneyandlove-network:
    driver: bridge