spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://172.26.3.244:3306/moneyandlovedb?autoReconnect=true&useUnicode=true&serverTimezone=Asia/Seoul"
    username: root
    password: 1234
  jpa:
    database: mysql
    properties:
      hibernate:
        storage_engine: innodb
    hibernate:
      ddl-auto: none
    open-in-view: false
  data:
    mongodb:
      uri: "mongodb://172.26.3.244:27017/moneyandlovedb"
  logging.level:
    org.hibernate.SQL: debug

OPENVIDU:
  URL: http://172.26.3.244:4443/
  SECRET: MY_SECRET

jwt:
  secret: nienteammoneyandlovenienteammoneyandlovenienteammoneyandlovenienteammoneyandlove
oauth2:
  client-id: ${KAKAO_CLIENT}
  client-secret: ${KAKAO_SECRET}
  redirect-uri: "http://localhost:3000/login/oauth2/callback"