spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT}
            client-secret: ${KAKAO_SECRET}
            redirect-uri: "http://localhost:3000/login/oauth2/callback"
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            scope: # kakao 개인 정보 동의 항목 설정의 ID 값
                - profile_nickname
                - profile_image
            client-name: kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/moneyandlovedb?autoReconnect=true&useUnicode=true&serverTimezone=Asia/Seoul"
    username: root
    password: 1234
  jpa:
    database: mysql
    properties:
      hibernate:
        storage_engine: innodb
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    show_sql: true
  data:
    mongodb:
      uri: "mongodb://localhost:27017/moneyandlovedb"
  logging.level:
    org.hibernate.SQL: debug

OPENVIDU:
  URL: http://localhost:4443/
  SECRET: MY_SECRET

jwt:
  secret: nienteammoneyandlove